name: aoc22
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  assets:
    - assets/day1_elvs.txt
    - assets/day2_strategy_guide.txt
    - assets/day3_rucksacks.txt
    - assets/day4_camp_cleanup.txt
    - assets/day5_supply_stacks.txt
    - assets/day6_tuning_trouble.txt
dependencies:
  collection: ^1.17.0
